language: rust
os:
  - linux
  - osx
cache: cargo
script:
  - cargo test -- --nocapture
  - cargo test -- --nocapture --ignored || true
  - cargo build --release
  - wget --method PUT --body-file=./target/release/wbmrs "https://transfer.sh/wbmrs-${TRAVIS_OS_NAME}" -O - -nv