install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
build: false
test_script:
  - cargo test -- --nocapture
  - cargo test -- --nocapture --ignored || true
  - cargo build --release
artifacts:
  - path: target\release\wbmrs.exe
    name: wbmrs-windows